#!/usr/bin/env bash

set -euo pipefail

readonly OH_MY_ZSH_DIR="$HOME/.oh-my-zsh"
readonly ZSHRC_FILE="$HOME/.zshrc"

log() {
    printf '[zsh-setup] %s\n' "$*"
}

run_as_root() {
    if [[ "${EUID}" -eq 0 ]]; then
        "$@"
    elif command -v sudo >/dev/null 2>&1; then
        sudo "$@"
    else
        printf 'This operation requires root privileges, but sudo is not installed.\n' >&2
        exit 1
    fi
}

install_packages() {
    if command -v apt-get >/dev/null 2>&1; then
        log "Installing Zsh and Git with apt"
        run_as_root apt-get update
        run_as_root apt-get install -y zsh git
    elif command -v dnf >/dev/null 2>&1; then
        log "Installing Zsh and Git with dnf"
        run_as_root dnf install -y zsh git
    elif command -v yum >/dev/null 2>&1; then
        log "Installing Zsh and Git with yum"
        run_as_root yum install -y zsh git
    elif command -v pacman >/dev/null 2>&1; then
        log "Installing Zsh and Git with pacman"
        run_as_root pacman -Sy --needed --noconfirm zsh git
    elif command -v brew >/dev/null 2>&1; then
        log "Installing Zsh and Git with Homebrew"
        brew install zsh git
    elif ! command -v zsh >/dev/null 2>&1 || ! command -v git >/dev/null 2>&1; then
        printf 'No supported package manager found. Install zsh and git first.\n' >&2
        exit 1
    fi
}

clone_or_update() {
    local repository="$1"
    local destination="$2"

    if [[ -d "$destination/.git" ]]; then
        log "Updating ${destination}"
        git -C "$destination" pull --ff-only
    elif [[ -e "$destination" ]]; then
        printf '%s exists but is not a Git repository. Move it aside and rerun this script.\n' "$destination" >&2
        exit 1
    else
        log "Installing ${destination}"
        git clone --depth=1 "$repository" "$destination"
    fi
}

write_zshrc() {
    local generated_file
    local backup_file

    generated_file="$(mktemp)"
    trap 'rm -f "${generated_file:-}"' RETURN

    cat >"$generated_file" <<'EOF'
# Generated by https://github.com/whr819987540/scripts/blob/main/zsh_install.sh

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# Keep startup predictable; update the installation by rerunning zsh_install.sh.
zstyle ':omz:update' mode disabled
DISABLE_AUTO_UPDATE=true

plugins=(
    git
    extract
    conda-zsh-completion
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source "$ZSH/oh-my-zsh.sh"

# Load personal environment variables without making them part of this file.
[[ -f "$HOME/.env_var" ]] && source "$HOME/.env_var"

# Initialize Conda from a portable location when it is installed.
if command -v conda >/dev/null 2>&1 && \
    __conda_setup="$(conda shell.zsh hook 2>/dev/null)"; then
    eval "$__conda_setup"
    unset __conda_setup
else
    unset __conda_setup
    for __conda_root in "$HOME/miniconda3" "$HOME/anaconda3"; do
        if [[ -f "$__conda_root/etc/profile.d/conda.sh" ]]; then
            source "$__conda_root/etc/profile.d/conda.sh"
            break
        fi
    done
    unset __conda_root
fi

# Homebrew uses different standard prefixes on Linux, Intel macOS and Apple Silicon.
if command -v brew >/dev/null 2>&1; then
    eval "$(brew shellenv)"
elif [[ -x /home/linuxbrew/.linuxbrew/bin/brew ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

[[ -f "$HOME/.config/clash-for-linux/profile.sh" ]] && \
    source "$HOME/.config/clash-for-linux/profile.sh"

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"

[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

# Persist history at shell exit while keeping concurrent terminals isolated.
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
unsetopt SHARE_HISTORY
unsetopt INC_APPEND_HISTORY
unsetopt INC_APPEND_HISTORY_TIME
EOF

    if [[ -f "$ZSHRC_FILE" ]] && cmp -s "$generated_file" "$ZSHRC_FILE"; then
        log "${ZSHRC_FILE} is already up to date"
        return
    fi

    if [[ -e "$ZSHRC_FILE" ]]; then
        backup_file="${ZSHRC_FILE}.backup.$(date +%Y%m%d%H%M%S)"
        cp -p "$ZSHRC_FILE" "$backup_file"
        log "Backed up the existing configuration to ${backup_file}"
    fi

    install -m 0644 "$generated_file" "$ZSHRC_FILE"
    log "Wrote ${ZSHRC_FILE}"
}

set_default_shell() {
    local zsh_path

    zsh_path="$(command -v zsh)"
    if [[ "${SHELL:-}" == "$zsh_path" ]]; then
        return
    fi

    if chsh -s "$zsh_path"; then
        log "Set the default shell to ${zsh_path}"
    else
        printf 'Could not change the default shell. Run: chsh -s %s\n' "$zsh_path" >&2
    fi
}

install_packages
clone_or_update "https://github.com/ohmyzsh/ohmyzsh.git" "$OH_MY_ZSH_DIR"
clone_or_update "https://github.com/conda-incubator/conda-zsh-completion.git" \
    "$OH_MY_ZSH_DIR/custom/plugins/conda-zsh-completion"
clone_or_update "https://github.com/zsh-users/zsh-autosuggestions.git" \
    "$OH_MY_ZSH_DIR/custom/plugins/zsh-autosuggestions"
clone_or_update "https://github.com/zsh-users/zsh-syntax-highlighting.git" \
    "$OH_MY_ZSH_DIR/custom/plugins/zsh-syntax-highlighting"
write_zshrc
set_default_shell

log "Installation complete. Start a new terminal or run: exec zsh"
